# FIFO, RAND, LFU, LRU
algoritmo = "FIFO"
# apenas FIFO implementado

# associativo - assocConj
mapeamento = "associativo"
# apenas associativo foi implementado

[linha]
tamanho = 1

[cache]
linhas = 2

[cpu]
quantidade = 2
